import type { ExampleEntry } from './types.js';

/**
 * Focused Data Grid laboratories in specialist-hub teaching order.
 *
 * Every entry is an app because each example owns the Classic desktop and centered template1 dialog.
 */
export const DATA_GRID_EXAMPLES = [
  {
    id: 'data-grid/quick-start',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/quick-start.ts',
    load: () => import('../../examples/data-grid/quick-start.js'),
  },
  {
    id: 'data-grid/data-sources',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/data-sources.ts',
    load: () => import('../../examples/data-grid/data-sources.js'),
  },
  {
    id: 'data-grid/typed-columns',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/typed-columns.ts',
    load: () => import('../../examples/data-grid/typed-columns.js'),
  },
  {
    id: 'data-grid/layout-freezing',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/layout-freezing.ts',
    load: () => import('../../examples/data-grid/layout-freezing.js'),
  },
  {
    id: 'data-grid/rendering',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/rendering.ts',
    load: () => import('../../examples/data-grid/rendering.js'),
  },
  {
    id: 'data-grid/sorting',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/sorting.ts',
    load: () => import('../../examples/data-grid/sorting.js'),
  },
  {
    id: 'data-grid/quick-filter',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/quick-filter.ts',
    load: () => import('../../examples/data-grid/quick-filter.js'),
  },
  {
    id: 'data-grid/advanced-filter',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/advanced-filter.ts',
    load: () => import('../../examples/data-grid/advanced-filter.js'),
  },
  {
    id: 'data-grid/selection-navigation',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/selection-navigation.ts',
    load: () => import('../../examples/data-grid/selection-navigation.js'),
  },
  {
    id: 'data-grid/row-mutations',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/row-mutations.ts',
    load: () => import('../../examples/data-grid/row-mutations.js'),
  },
  {
    id: 'data-grid/editing-lifecycle',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/editing-lifecycle.ts',
    load: () => import('../../examples/data-grid/editing-lifecycle.js'),
  },
  {
    id: 'data-grid/editor-types',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/editor-types.ts',
    load: () => import('../../examples/data-grid/editor-types.js'),
  },
  {
    id: 'data-grid/custom-editor',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/custom-editor.ts',
    load: () => import('../../examples/data-grid/custom-editor.js'),
  },
  {
    id: 'data-grid/dirty-commit',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/dirty-commit.ts',
    load: () => import('../../examples/data-grid/dirty-commit.js'),
  },
  {
    id: 'data-grid/validation',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/validation.ts',
    load: () => import('../../examples/data-grid/validation.js'),
  },
  {
    id: 'data-grid/lifecycle-states',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/lifecycle-states.ts',
    load: () => import('../../examples/data-grid/lifecycle-states.js'),
  },
  {
    id: 'data-grid/aggregates',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/aggregates.ts',
    load: () => import('../../examples/data-grid/aggregates.js'),
  },
  {
    id: 'data-grid/master-detail',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/master-detail.ts',
    load: () => import('../../examples/data-grid/master-detail.js'),
  },
  {
    id: 'data-grid/windowed',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/windowed.ts',
    load: () => import('../../examples/data-grid/windowed.js'),
  },
  {
    id: 'data-grid/large-memory',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/large-memory.ts',
    load: () => import('../../examples/data-grid/large-memory.js'),
  },
  {
    id: 'data-grid/export',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/export.ts',
    load: () => import('../../examples/data-grid/export.js'),
  },
  {
    id: 'data-grid/variants-personalization',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/variants-personalization.ts',
    load: () => import('../../examples/data-grid/variants-personalization.js'),
  },
  {
    id: 'data-grid/theming-accessibility',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/theming-accessibility.ts',
    load: () => import('../../examples/data-grid/theming-accessibility.js'),
  },
  {
    id: 'data-grid/performance-boundaries',
    category: 'data-grid',
    kind: 'app',
    sourcePath: 'examples/data-grid/performance-boundaries.ts',
    load: () => import('../../examples/data-grid/performance-boundaries.js'),
  },
] as const satisfies readonly ExampleEntry[];
