import type { ExampleEntry } from './types.js';

/** Concept-guide laboratories in course order, each owning the complete template1 application shell. */
export const GUIDE_EXAMPLES = [
  {
    id: 'guides/introduction-runtime',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/introduction-runtime.ts',
    load: () => import('../../examples/guides/introduction-runtime.js'),
  },
  {
    id: 'guides/layout-flow',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/layout-flow.ts',
    load: () => import('../../examples/guides/layout-flow.js'),
  },
  {
    id: 'guides/layout-overlays',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/layout-overlays.ts',
    load: () => import('../../examples/guides/layout-overlays.js'),
  },
  {
    id: 'guides/reactive-graph',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/reactive-graph.ts',
    load: () => import('../../examples/guides/reactive-graph.js'),
  },
  {
    id: 'guides/reactive-lifetimes',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/reactive-lifetimes.ts',
    load: () => import('../../examples/guides/reactive-lifetimes.js'),
  },
  {
    id: 'guides/views-focus-traversal',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/views-focus-traversal.ts',
    load: () => import('../../examples/guides/views-focus-traversal.js'),
  },
  {
    id: 'guides/views-focus-modality',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/views-focus-modality.ts',
    load: () => import('../../examples/guides/views-focus-modality.js'),
  },
  {
    id: 'guides/event-routing',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/event-routing.ts',
    load: () => import('../../examples/guides/event-routing.js'),
  },
  {
    id: 'guides/command-precedence',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/command-precedence.ts',
    load: () => import('../../examples/guides/command-precedence.js'),
  },
  {
    id: 'guides/clipboard-boundary',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/clipboard-boundary.ts',
    load: () => import('../../examples/guides/clipboard-boundary.js'),
  },
  {
    id: 'guides/cell-width',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/cell-width.ts',
    load: () => import('../../examples/guides/cell-width.js'),
  },
  {
    id: 'guides/glyph-fallback',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/glyph-fallback.ts',
    load: () => import('../../examples/guides/glyph-fallback.js'),
  },
  {
    id: 'guides/viewport-strategies',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/viewport-strategies.ts',
    load: () => import('../../examples/guides/viewport-strategies.js'),
  },
  {
    id: 'guides/virtual-collections',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/virtual-collections.ts',
    load: () => import('../../examples/guides/virtual-collections.js'),
  },
  {
    id: 'guides/application-chrome',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/application-chrome.ts',
    load: () => import('../../examples/guides/application-chrome.js'),
  },
  {
    id: 'guides/application-bodies',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/application-bodies.ts',
    load: () => import('../../examples/guides/application-bodies.js'),
  },
  {
    id: 'guides/dialog-results',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/dialog-results.ts',
    load: () => import('../../examples/guides/dialog-results.js'),
  },
  {
    id: 'guides/modal-workflows',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/modal-workflows.ts',
    load: () => import('../../examples/guides/modal-workflows.js'),
  },
  {
    id: 'guides/cancellable-work',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/cancellable-work.ts',
    load: () => import('../../examples/guides/cancellable-work.js'),
  },
  {
    id: 'guides/latest-result-wins',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/latest-result-wins.ts',
    load: () => import('../../examples/guides/latest-result-wins.js'),
  },
  {
    id: 'guides/form-state-validation',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/form-state-validation.ts',
    load: () => import('../../examples/guides/form-state-validation.js'),
  },
  {
    id: 'guides/form-async-submit',
    category: 'guides',
    kind: 'app',
    sourcePath: 'examples/guides/form-async-submit.ts',
    load: () => import('../../examples/guides/form-async-submit.js'),
  },
] as const satisfies readonly ExampleEntry[];
